server:
    port: 8200

spring:
    application:
        name: issue-service

    jpa:
        hibernate:
            ddl-auto: update
    datasource:
        url: jdbc:mysql://localhost:3306/projectmanagement_issue_service
        username: root
        password: Mterstegen#1
        driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8700/eureka