server:
    port: 8100

spring:
    application:
        name: project-service

    jpa:
        hibernate:
            ddl-auto: update

    mail:
        host: smtp.gmail.com
        port: 587
        username: tanay22pandey@gmai.com
        password: hpbe eweo qpho csnd
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true

    datasource:
        url: jdbc:mysql://localhost:3306/projectmanagement_project_service
        username: root
        password: Mterstegen#1
        driver-class-name: com.mysql.cj.jdbc.Driver


